name: build

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'

    - name: Install dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.87.0'
        extended: true
    - name: Build
      run: hugo -D
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'