name: build

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'

    - name: Install dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.87.0'
        extended: true

    - name: Build
      run: hugo -D
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # external_repository: hkloudou/hkloudou.github.io
        # publish_branch: gh-pages
        publish_dir: ./public
        # cname: marwin.cn
        commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
    # - name: Deploy
    #   env:
    #     TZ: Asia/Shanghai
    #     DEPLOY_REPO: hkloudou/hkloudou.github.io
    #     DEPLOY_BRANCH: main
    #     PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    #   run: |
    #     cd ./public && git init
    #     git config user.name "hkloudou"
    #     git config user.email "hkloudou@gmail.com"
    #     git add .
    #     git commit -m "Automated Deployment @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
    #     git push --force --quiet "https://$PERSONAL_TOKEN@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH